### ISSUE TITLE
Execute a command after starting the container

### ISSUE THREAD

**Issue by unixfox** [ix-ai/swarm-launcher#2]
I need to launch a container in two networks but unfortunately I'm not able to do it from the `LAUNCH_EXTRA_ARGS` env.
The command needed to connect a container into a second network is this one: `docker network connect second_network container`.

Do you think it would feasible to add this functionality to `swarm-launcher`?

**Comment by tlex** [comment]
At first I couldn't figure out a way, but I've found something. Will create a version for you to try out.

**Comment by tlex** [comment]
Please take a look at the [switch-docker-compose](https://github.com/ix-ai/swarm-launcher/tree/switch-docker-compose) branch. The image for it is `ixdotai/swarm-launcher:dev-branch`

**Comment by tlex** [comment]
Fixed by #4
