### ISSUE TITLE
PID mode

### ISSUE THREAD

**Issue by dasos** [ix-ai/swarm-launcher#25]
Hi. Could support for PID mode be added? As per here: https://docs.docker.com/compose/compose-file/#pid Thanks!

**Comment by tlex** [comment]
Thanks for the feature request.

I've added (as seen in the commit) `LAUNCH_PID_MODE` which can be set to `host`.

You can take it for a spin by using either the image `ixdotai/swarm-launcher:dev-master` or `registry.gitlab.com/ix.ai/swarm-launcher:dev-master`.

I'll create a new release by the end of the week.

**Comment by dasos** [comment]
Wow, thank you, that was fast! It looks good, thank you very much! :) 👍

**Comment by tlex** [comment]
Thanks for the feedback. I've released [v0.12.0](https://gitlab.com/ix.ai/swarm-launcher/-/tags/v0.12.0) now.
