### ISSUE TITLE
Feature Request - support IPv6

### ISSUE THREAD

**Issue by FrancisHG** [ix-ai/swarm-launcher#32]
Hello, this application is great. Cannot believe Docker Swarm does not support some of this already. Any plans for EXT_NETWORKS_IPV6 support?

**Comment by tlex** [comment]
Thank you for the feature request. I have added support for both `LAUNCH_EXT_NETWORKS_IPV6` and `LAUNCH_EXT_NETWORKS_MIXED`  (for when you have both IPv4 and IPv6 which you want to manually set).

Unfortunately, I cannot test it myself, since I don't manually assign IP addresses. You can try it out by using the image `ixdotai/swarm-launcher:dev-branch`

**Comment by tlex** [comment]
The new environment variables are now supported by v0.18.0

**Comment by FrancisHG** [comment]
@tlex Hi, sorry it took a while to get around to testing this.

I think this feature (MIXED) and IPV6 standalone do not work as intended with external networks
Both
LAUNCH_EXT_NETWORKS_IPV6 and LAUNCH_EXT_NETWORKS_MIXED do not create a external attachable network in the rendered compose text. I think this is around Line 374 in entrypoint.sh, note that only for LAUNCH_EXT_NETWORKS and LAUNCH_EXT_NETWORKS_IPV4 does the script generate the required network parts.

**Comment by tlex** [comment]
Well, better later than never :slightly_smiling_face: 

I'll take a look at it.

**Comment by tlex** [comment]
The new image is built. You can try it out:
```
docker pull ghcr.io/ix-ai/swarm-launcher:dev-branch@sha256:a9515ad3b6f9d97ed1c8577c2a8c9ace5c406fcc83895cd27fd8e1a94d83315d`

**Comment by FrancisHG** [comment]
> The new image is built. You can try it out:
> 
> ```
> docker pull ghcr.io/ix-ai/swarm-launcher:dev-branch@sha256:a9515ad3b6f9d97ed1c8577c2a8c9ace5c406fcc83895cd27fd8e1a94d83315d`
> ```

awesome, thanks for quick turnaround! i will test later today, wife has lasik surgery this morning :)

**Comment by FrancisHG** [comment]
I tried to test but my Docker isn't complying... I added 
    image: ghcr.io/ix-ai/swarm-launcher:dev-branch

but my SHA hash is not matching the one you posted. Also the tag shows <unknown>, i think the GHCR registry is not setup on this node. I'll give it another shot later, need some rest.

**Comment by tlex** [comment]
I'm always pushing to all three registries, so you can use any of them:
```
registry.gitlab.com/ix.ai/swarm-launcher:dev-branch
ghcr.io/ix-ai/swarm-launcher:dev-branch
ixdotai/swarm-launcher:dev-branch
```

I have just verified and they are the same:
```
[tlex@McThink]-[ ~ ]$ docker pull ixdotai/swarm-launcher:dev-branch
dev-branch: Pulling from ixdotai/swarm-launcher
f56be85fc22e: Already exists 
e08716d9a766: Pull complete 
417eafcf9f32: Pull complete 
Digest: sha256:a9515ad3b6f9d97ed1c8577c2a8c9ace5c406fcc83895cd27fd8e1a94d83315d
Status: Downloaded newer image for ixdotai/swarm-launcher:dev-branch
docker.io/ixdotai/swarm-launcher:dev-branch
[tlex@McThink]-[ ~ ]$ docker pull registry.gitlab.com/ix.ai/swarm-launcher:dev-branch
dev-branch: Pulling from ix.ai/swarm-launcher
Digest: sha256:a9515ad3b6f9d97ed1c8577c2a8c9ace5c406fcc83895cd27fd8e1a94d83315d
Status: Downloaded newer image for registry.gitlab.com/ix.ai/swarm-launcher:dev-branch
registry.gitlab.com/ix.ai/swarm-launcher:dev-branch
[tlex@McThink]-[ ~ ]$ docker pull ghcr.io/ix-ai/swarm-launcher:dev-branch
dev-branch: Pulling from ix-ai/swarm-launcher
Digest: sha256:a9515ad3b6f9d97ed1c8577c2a8c9ace5c406fcc83895cd27fd8e1a94d83315d
Status: Downloaded newer image for ghcr.io/ix-ai/swarm-launcher:dev-branch
ghcr.io/ix-ai/swarm-launcher:dev-branch
[tlex@McThink]-[ ~ ]$ 
```

**Comment by FrancisHG** [comment]
> I'm always pushing to all three registries, so you can use any of them:
> 
> ```
> registry.gitlab.com/ix.ai/swarm-launcher:dev-branch
> ghcr.io/ix-ai/swarm-launcher:dev-branch
> ixdotai/swarm-launcher:dev-branch
> ```
> 
> I have just verified and they are the same:
> 
> ```
> [tlex@McThink]-[ ~ ]$ docker pull ixdotai/swarm-launcher:dev-branch
> dev-branch: Pulling from ixdotai/swarm-launcher
> f56be85fc22e: Already exists 
> e08716d9a766: Pull complete 
> 417eafcf9f32: Pull complete 
> Digest: sha256:a9515ad3b6f9d97ed1c8577c2a8c9ace5c406fcc83895cd27fd8e1a94d83315d
> Status: Downloaded newer image for ixdotai/swarm-launcher:dev-branch
> docker.io/ixdotai/swarm-launcher:dev-branch
> [tlex@McThink]-[ ~ ]$ docker pull registry.gitlab.com/ix.ai/swarm-launcher:dev-branch
> dev-branch: Pulling from ix.ai/swarm-launcher
> Digest: sha256:a9515ad3b6f9d97ed1c8577c2a8c9ace5c406fcc83895cd27fd8e1a94d83315d
> Status: Downloaded newer image for registry.gitlab.com/ix.ai/swarm-launcher:dev-branch
> registry.gitlab.com/ix.ai/swarm-launcher:dev-branch
> [tlex@McThink]-[ ~ ]$ docker pull ghcr.io/ix-ai/swarm-launcher:dev-branch
> dev-branch: Pulling from ix-ai/swarm-launcher
> Digest: sha256:a9515ad3b6f9d97ed1c8577c2a8c9ace5c406fcc83895cd27fd8e1a94d83315d
> Status: Downloaded newer image for ghcr.io/ix-ai/swarm-launcher:dev-branch
> ghcr.io/ix-ai/swarm-launcher:dev-branch
> [tlex@McThink]-[ ~ ]$ 
> ```

weird, if i do docker image pull it shows the correct hash, but if I examine the container and registry in Portainer it shows the incorrect hash.

`Image sha256:7e7ed07f3127e6eb5196965cbf9a7a498199626e1c11b564f6bc40e430ff97fb`


```
pranch_ssh@hermes:~ $ sudo docker pull ixdotai/swarm-launcher:dev-branch
dev-branch: Pulling from ixdotai/swarm-launcher
c41833b44d91: Pull complete 
1293f5c0cecd: Pull complete 
144a7e6f6021: Pull complete 
Digest: sha256:a9515ad3b6f9d97ed1c8577c2a8c9ace5c406fcc83895cd27fd8e1a94d83315d
Status: Downloaded newer image for ixdotai/swarm-launcher:dev-branch
docker.io/ixdotai/swarm-launcher:dev-branch
```

**Comment by FrancisHG** [comment]
I confirmed I am pulling the correct image, but still getting error before where the network does not exist in `networks `section when using `LAUNCH_EXT_NETWORKS_MIXED`

ie: `LAUNCH_EXT_NETWORKS_MIXED: 'pranchnet-192.168.60.140-2001:3984:3989:19::140'`

**Comment by tlex** [comment]
Can you please provide the full log output? I want to see the internally 
generated docker compose file as well.

Thanks

**Comment by FrancisHG** [comment]
Sure

`  sshd-bootstrapper:
    deploy:
      replicas: 1
      labels:
        ai.ix.auto-update: 'true'
    image: registry.gitlab.com/ix.ai/swarm-launcher:dev-branch
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:rw'
    environment:
      LAUNCH_IMAGE: panubo/sshd:latest
      LAUNCH_PULL: 'true'
      LAUNCH_EXT_NETWORKS: 'local_default'
      #LAUNCH_EXT_NETWORKS_IPV4: 'pranchnet:192.168.60.140'
      #LAUNCH_EXT_NETWORKS_IPV6: 'pranchnet:2001:3984:3989:19::140'
      LAUNCH_EXT_NETWORKS_MIXED: 'pranchnet-192.168.60.140-2001:3984:3989:19::140'
      LAUNCH_ENVIRONMENTS: 'SSH_USERS=<REDACTED>:<REDACTED>:<REDACTED> TCP_FORWARDING=true'
      LAUNCH_VOLUMES: '/etc/timezone:/etc/timezone:ro <REDACTED>sshd/authorized_keys:/etc/authorized_keys/pranch <REDACTED>/sshd/config/ssh/keys:/etc/ssh/keys <REDACTED>/sshd/entrypoint.d:/etc/entrypoint.d'
      LAUNCH_PROJECT_NAME: sshd
      LAUNCH_CONTAINER_NAME: sshd
      LOGIN_USER: francishg
      LOGIN_PASSWORD_FILE: <REDACTED>`

`
swarm-launcher: Doing startup check
swarm-launcher: Testing compose file:
version: "3.8"
  "bzE6Ye":
    image: "panubo/sshd:latest"
    restart: "no"
      - /mnt/docker/sshd/config/ssh/keys:/etc/ssh/keys
    labels:
      - /mnt/docker/sshd/entrypoint.d:/etc/entrypoint.d
      - "ai.ix.started-by=ix.ai/swarm-launcher"
    container_name: "sshd"
    environment:
      - SSH_USERS=<REDACTED>:<REDACTED>:<REDACTED>
    networks:
      local_default:
      pranchnet:
        ipv4_address: '192.168.60.140'
        ipv6_address: '2001:3984:3989:19::140'

:
  local_default:
    external: true
swarm-launcher: -----------------------------------
service "7cXgjY" refers to undefined network pranchnet: invalid compose project`

**Comment by tlex** [comment]
Thanks for the info.

I have the feeling I'm reaching the readability limits of bash.

I haven't noticed that a whole block is still missing. I've added it now.

You can test:
```
ixdotai/swarm-launcher:dev-branch@sha256:9c591ffa04660e643721425225a2bb3fd09289b2c8d8085498eb04e97ea24706
``` 

P.S.
* The commented out line `#LAUNCH_EXT_NETWORKS_IPV6: 'pranchnet:2001:3984:3989:19::140'` should use `-` instead of `:` between `pranchnet` and the IPv6
* I'm a bit concerned about that funky character and the empty line with just `:`. I hope it's the result of some strange behavior of the terminal and you actually see `networks:` instead.

**Comment by FrancisHG** [comment]
> Thanks for the info.
> 
> I have the feeling I'm reaching the readability limits of bash.
> 
> I haven't noticed that a whole block is still missing. I've added it now.
> 
> You can test:
> 
> ```
> ixdotai/swarm-launcher:dev-branch@sha256:9c591ffa04660e643721425225a2bb3fd09289b2c8d8085498eb04e97ea24706
> ```
> 
> P.S.
> 
> * The commented out line `#LAUNCH_EXT_NETWORKS_IPV6: 'pranchnet:2001:3984:3989:19::140'` should use `-` instead of `:` between `pranchnet` and the IPv6
> * I'm a bit concerned about that funky character and the empty line with just `:`. I hope it's the result of some strange behavior of the terminal and you actually see `networks:` instead.

I actually have been breaking out my services to docker-compose.yml files which I pass-through to swarm-launcher. I just became aware of this feature and it seems easier for me.
