### ISSUE TITLE
hard coded docker-compose.yml file

### ISSUE THREAD

**Issue by SkazochnikZlodey** [ix-ai/swarm-launcher#35]
Hello if possible in file entrypoint.sh line 70 
replace 
COMPOSE_FILE="/docker-compose.yml"
to
COMPOSE_FILE=${LAUNCH_COMPOSE_FILE:-/docker-compose.yml}

**Comment by tlex** [comment]
Thanks for opening this issue.

It's not complicated to do, but I'm not sure it's necessary.

Docker allows you to mount any file with any destination file name. It just requires the [volumes long syntax](https://docs.docker.com/compose/compose-file/05-services/#long-syntax-5) for it to work.
