### ISSUE TITLE
Add shm-size option

### ISSUE THREAD

**Issue by dadcoachengineer** [ix-ai/swarm-launcher#36]
Is it possible to add the shm-size option? Is there another way to pass options this wonderful launcher does not support?

**Comment by tlex** [comment]
Released in [v0.20.0](https://github.com/ix-ai/swarm-launcher/releases/tag/v0.20.0)

**Comment by dadcoachengineer** [comment]
Thank you!

Can you provide syntax for providing your own compose.yaml file rather than entrypoint.sh building it?

**Comment by tlex** [comment]
This container uses `docker compose`, so any valid [compose file](https://docs.docker.com/compose/compose-file/) should do it.
